---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/8/2023 7:12 PM
---

return {
    run = {
        main = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 473,
            height = 466,
            frame_count = 1,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.66,
            animation_speed = 0.4,
        },
        shadow = {
            shift = {6, 0}
        },
        team = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run_teamcolour-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run_teamcolour-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 473,
            height = 466,
            frame_count = 1,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.66,
            animation_speed = 0.4,
        },
        glow = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run_mask-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run_mask-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 473,
            height = 466,
            frame_count = 1,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.66,
            animation_speed = 0.4,
            blend_mode = "additive"
        },
        effect = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-effect-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-effect-1.png",
            },
            slice = 2,
            lines_per_file = 8,
            line_length = 2,
            width = 473,
            height = 466,
            frame_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.66,
            animation_speed = 0.4,
            draw_as_glow = true,
            blend_mode = "additive"
        }
    },
    attack = {
        main = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 473,
            height = 466,
            frame_count = 1,
            repeat_count = 10,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.66,
            animation_speed = 0.4,
        },
        shadow = {
            shift = {6, 0}
        },
        team = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run_teamcolour-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run_teamcolour-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 473,
            height = 466,
            frame_count = 1,
            repeat_count = 10,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.66,
            animation_speed = 0.4,
        },
        glow = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run_mask-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-run_mask-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 473,
            height = 466,
            frame_count = 1,
            repeat_count = 10,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.66,
            animation_speed = 0.4,
            blend_mode = "additive"
        },
        effect = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-effect-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/battlecruiser/battlecruiser-effect-1.png",
            },
            slice = 2,
            lines_per_file = 8,
            line_length = 2,
            width = 473,
            height = 466,
            frame_count = 2,
            repeat_count = 5,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.66,
            animation_speed = 0.4,
            draw_as_glow = true,
            blend_mode = "additive"
        },
        -- hmm.. why this crash with larger than 8096 pixel?
        --light = {
        --    filename = "__erm_terran_hd_assets__/graphics/entity/projectiles/battlecruiser/battlecruiser_yamato_charging.png",
        --    width = 806,
        --    height = 701,
        --    scale = 0.66,
        --    frame_count = 10,
        --    animation_speed = 0.4,
        --    direction_count = 1,
        --    axially_symmetrical = false,
        --}
    }
}