---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/8/2023 7:12 PM
---

return {
    run = {
        main =                         {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/dropship/dropship-run.png",
            width = 240,
            height = 252,
            frame_count = 1,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        },
        shadow = {
            shift = {4, 0}
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/dropship/dropship-run_teamcolour.png",
            width = 240,
            height = 252,
            frame_count = 1,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        },
        effect = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/dropship/dropship-effect.png",
            width = 240,
            height = 252,
            frame_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
            draw_as_glow = true,
            blend_mode = "additive"
        }
    }
}