---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/8/2023 7:12 PM
---

return {
    run = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/firebat_mkII/firebat_mkII-run.png",
            width = 402,
            height = 402,
            frame_count = 17,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4
        },
        shadow = {
            shift = {0.2, 0}
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/firebat_mkII/firebat_mkII-run_teamcolour.png",
            width = 402,
            height = 402,
            frame_count = 17,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4,
        }
    },
    attack = {
        main  = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/firebat_mkII/firebat_mkII-attack.png",
            width = 402,
            height = 402,
            frame_count = 13,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4,
            draw_as_glow = true,
        },
        shadow = {
            shift = {0.2, 0}
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/firebat_mkII/firebat_mkII-attack_teamcolour.png",
            width = 402,
            height = 402,
            frame_count = 13,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4,
        },
        effect = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/firebat/firebat-effect-flamer.png",
            width = 512,
            height = 512,
            frame_count = 13,
            axially_symmetrical = false,
            direction_count = 16,
            animation_speed = 0.4,
            scale = 0.5,
            draw_as_glow = true,
        },
        light = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/weapon_flash-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/weapon_flash-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 515,
            height = 531,
            frame_count = 1,
            repeat_count = 13,
            direction_count = 16,
            animation_speed = 0.4,
            scale = 0.4
        }
    }
}