---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/8/2023 7:12 PM
---

return {
    run = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/ghost_mkII/ghost_mkII-run.png",
            width = 402,
            height = 402,
            frame_count = 20,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4
        },
        shadow = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/ghost_mkII/ghost_mkII-run_shadow.png",
            width = 402,
            height = 402,
            frame_count = 20,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/ghost_mkII/ghost_mkII-run_teamcolour.png",
            width = 402,
            height = 402,
            frame_count = 20,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4,
        }
    },
    attack = {
        main  = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/ghost_mkII/ghost_mkII-attack.png",
            width = 402,
            height = 402,
            frame_count = 20,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.4,
            animation_speed = 0.4,
            draw_as_glow = true
        },
        shadow = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/ghost_mkII/ghost_mkII-attack_shadow.png",
            width = 402,
            height = 402,
            frame_count = 20,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/ghost_mkII/ghost_mkII-attack_teamcolour.png",
            width = 402,
            height = 402,
            frame_count = 20,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4,
        }
    }
}