---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/8/2023 7:12 PM
---

return {
    run = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/goliath/goliath-run-bottom.png",
            width = 286,
            height = 299,
            frame_count = 10,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        shadow = {
            shift = {0.2, 0}
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/goliath/goliath-run-bottom_teamcolour.png",
            width = 286,
            height = 299,
            frame_count = 10,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        }
    },
    attack = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/goliath/goliath-attack-bottom.png",
            width = 286,
            height = 299,
            frame_count = 1,
            repeat_count = 8,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        shadow = {
            shift = {0.2, 0}
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/goliath/goliath-attack-bottom.png",
            width = 286,
            height = 299,
            frame_count = 1,
            repeat_count = 8,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        }
    }
}