---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/8/2023 7:12 PM
---

return {
    run = {
        main = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/science_vessel/science_vessel-run-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/science_vessel/science_vessel-run-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 384,
            height = 522,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4
        },
        shadow = {
            shift = {4,0}
        },
        team = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/science_vessel/science_vessel-run_teamcolour-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/science_vessel/science_vessel-run_teamcolour-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 384,
            height = 522,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.4
        },
        glow = {
                filenames = {
                    "__erm_terran_hd_assets__/graphics/entity/units/science_vessel/science_vessel-run_mask-0.png",
                    "__erm_terran_hd_assets__/graphics/entity/units/science_vessel/science_vessel-run_mask-1.png",
                },
                slice = 1,
                lines_per_file = 8,
                line_length = 1,
                width = 384,
                height = 522,
                frame_count = 1,
                axially_symmetrical = false,
                direction_count = 16,
                scale = 0.5,
                animation_speed = 0.4,
                blend_mode = "additive"
        }
    }
}