---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/8/2023 7:12 PM
---

return {
    run = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-turret.png",
            width = 512,
            height = 506,
            frame_count = 1,
            repeat_count = 3,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-turret_teamcolour.png",
            width = 512,
            height = 506,
            frame_count = 1,
            repeat_count = 3,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        glow = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-turret_mask.png",
            width = 512,
            height = 506,
            frame_count = 1,
            repeat_count = 3,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
            blend_mode = "additive"
        }
    },
    attack = {
        main =           {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-turret.png",
            width = 512,
            height = 506,
            frame_count = 1,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.2, 0 }
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-turret_teamcolour.png",
            width = 512,
            height = 506,
            frame_count = 1,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        glow = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-turret_mask.png",
            width = 512,
            height = 506,
            frame_count = 1,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
            blend_mode = "additive"
        },
        effect = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-turret_effect.png",
            width = 512,
            height = 506,
            frame_count = 1,
            direction_count = 16,
            scale = 0.375,
            draw_as_glow = true,
            animation_speed = 0.4
        },
        light = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/weapon_flash-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/weapon_flash-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 515,
            height = 531,
            frame_count = 1,
            direction_count = 16,
            animation_speed = 0.4,
            scale = 0.8
        }
    }
}