---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/23/2023 10:58 PM
---

return {
    run = {
        main = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-run-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-run-1.png",
            },
            slice = 10,
            lines_per_file = 8,
            line_length = 10,
            width = 804,
            height = 804,
            frame_count = 10,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        },
        shadow = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-run_shadow-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-run_shadow-1.png",
            },
            slice = 10,
            lines_per_file = 8,
            line_length = 10,
            width = 804,
            height = 804,
            frame_count = 10,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        },
        team = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-run_teamcolour-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-run_teamcolour-1.png",
            },
            slice = 10,
            lines_per_file = 8,
            line_length = 10,
            width = 804,
            height = 804,
            frame_count = 10,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        }
    },
    attack = {
        main = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-attack-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-attack-1.png",
            },
            slice = 4,
            lines_per_file = 8,
            line_length = 4,
            width = 804,
            height = 804,
            frame_count = 4,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        },
        shadow = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-attack_shadow-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-attack_shadow-1.png",
            },
            slice = 4,
            lines_per_file = 8,
            line_length = 4,
            width = 804,
            height = 804,
            frame_count = 4,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        team = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-attack_teamcolour-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/siege_tank_mkII/siege_tank_mkII-attack_teamcolour-1.png",
            },
            slice = 4,
            lines_per_file = 8,
            line_length = 4,
            width = 804,
            height = 804,
            frame_count = 4,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4
        },
        effect = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-turret_effect.png",
            width = 512,
            height = 506,
            frame_count = 1,
            repeat_count = 4,
            direction_count = 16,
            scale = 0.5,
            draw_as_glow = true,
            animation_speed = 0.4
        },
        light = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/weapon_flash-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/weapon_flash-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 515,
            height = 531,
            frame_count = 1,
            repeat_count = 4,
            direction_count = 16,
            animation_speed = 0.4,
            scale = 1
        }
    }
}