---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/8/2023 7:12 PM
---

return {
    run = {
        main =                     {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-body-run.png",
            width = 512,
            height = 506,
            repeat_count = 3,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.3, 0.0 }
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-body_teamcolour.png",
            width = 512,
            height = 506,
            frame_count = 1,
            repeat_count = 3,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        }
    },
    attack = {
        main =                     {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-body-attack.png",
            width = 512,
            height = 506,
            repeat_count = 3,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.3, 0.0 }
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/siege_tank/siege_tank-body_teamcolour.png",
            width = 512,
            height = 506,
            frame_count = 1,
            repeat_count = 3,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        }
    }
}