---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/8/2023 7:12 PM
---

return {
    run = {
        main = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/valkyrie/valkyrie-run-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/valkyrie/valkyrie-run-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 523,
            height = 519,
            frame_count = 1,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 4, 0 }
        },
        team = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/valkyrie/valkyrie-run_teamcolour-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/valkyrie/valkyrie-run_teamcolour-1.png",
            },
            slice = 1,
            lines_per_file = 8,
            line_length = 1,
            width = 523,
            height = 519,
            frame_count = 1,
            repeat_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        glow = {
            filenames = {
                "__erm_terran_hd_assets__/graphics/entity/units/valkyrie/valkyrie-effect-0.png",
                "__erm_terran_hd_assets__/graphics/entity/units/valkyrie/valkyrie-effect-1.png",
            },
            slice = 2,
            lines_per_file = 8,
            line_length = 2,
            width = 523,
            height = 519,
            frame_count = 2,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
            blend_mode = "additive"
        }
    }
}