---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/8/2023 7:12 PM
---

return {
    run = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/vulture/vulture-run.png",
            width = 430,
            height = 400,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
        shadow = {
            shift = { 0.2, 0}
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/units/vulture/vulture-run_teamcolour.png",
            width = 430,
            height = 400,
            frame_count = 1,
            axially_symmetrical = false,
            direction_count = 16,
            scale = 0.375,
            animation_speed = 0.4,
        },
    },
}