---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/26/2023 11:37 PM
---
--- This file lists all callable animation functions.

local AnimationDB = require('animation_db')

