---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/1/2023 11:51 PM
---


return {
    firebat = {
        explosion = {
            glow = {
                filename = "__erm_terran_hd_assets__/graphics/entity/projectiles/shockbomb_explosion.png",
                width = 400,
                height = 432,
                scale = 0.25,
                frame_count = 14,
                animation_speed = 0.4,
            }
        }
    },
    small_building_death = {
        explosion = {
            glow = {
                filename = "__erm_terran_hd_assets__/graphics/entity/buildings/building_death/terran_building_explosion_small.png",
                width = 583,
                height = 561,
                frame_count = 9,
                animation_speed = 0.2,
                direction_count = 1,
                scale = 0.375,
            }
        }
    },
    large_building_death = {
        explosion = {
            glow = {
                filename = "__erm_terran_hd_assets__/graphics/entity/buildings/building_death/terran_building_explosion_large.png",
                width = 819,
                height = 661,
                frame_count = 10,
                animation_speed = 0.2,
                direction_count = 1,
                scale = 0.375,
            }
        }
    },
    ghost_death = {
        explosion = {
            main = {
                filename = "__erm_terran_hd_assets__/graphics/entity/units/ghost/ghost-death.png",
                width = 310,
                height = 238,
                frame_count = 8,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.5,
                animation_speed = 0.2,
            }
        }
    },
    marine_death = {
        explosion = {
            main = {
                filename = "__erm_terran_hd_assets__/graphics/entity/units/marine/marine-death.png",
                width = 313,
                height = 226,
                frame_count = 8,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.5,
                animation_speed = 0.2,
            }
        }
    },
    medic_death = {
        explosion = {
            main = {
                filename = "__erm_terran_hd_assets__/graphics/entity/units/medic/medic-death.png",
                width = 322,
                height = 266,
                frame_count = 8,
                direction_count = 1,
                axially_symmetrical = false,
                scale = 0.5,
                animation_speed = 0.2,
            }
        }
    },
    small_rubble = {
        corpse ={
            main = {
                filename = "__erm_terran_hd_assets__/graphics/entity/buildings/building_death/terran_small_rubble.png",
                width = 390,
                height = 390,
                variation_count = 4,
                frame_count = 1,
                direction_count = 1,
                scale = 0.5,
            }
        }
    },
    large_rubble = {
        corpse ={
            main = {
                filename = "__erm_terran_hd_assets__/graphics/entity/buildings/building_death/terran_large_rubble.png",
                width = 525,
                height = 525,
                frame_count = 1,
                direction_count = 1,
                scale = 0.5,
            }
        }
    }
}