---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/9/2023 10:19 PM
---

return {
    folded = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/bunker/bunker.png",
            width = 392,
            height = 529,
            frame_count = 1,
            direction_count = 1,
            scale = 0.5,
            animation_speed = 0.2,
        },
        shadow = {
            shift = {0.25, 0}
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/bunker/bunker_teamcolour.png",
            flags = { "mask" },
            width = 392,
            height = 529,
            frame_count = 1,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5,
        }
    },
    attack = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/bunker/bunker-attack.png",
            width = 392,
            height = 529,
            frame_count = 2,
            repeat_count = 3,
            direction_count = 8,
            animation_speed = 0.4,
            scale = 0.5,
        },
        shadow = {
            shift = {0.25, 0}
        },
        glow = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/bunker/bunker-attack_mask.png",
            width = 392,
            height = 529,
            frame_count = 2,
            repeat_count = 3,
            direction_count = 8,
            animation_speed = 0.4,
            scale = 0.5,
            blend_mode = "additive",
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/bunker/bunker-attack_teamcolour.png",
            width = 392,
            height = 529,
            frame_count = 2,
            repeat_count = 3,
            direction_count = 8,
            scale = 0.5,
            animation_speed = 0.4,
        },
        light = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/bunker/bunker-flash.png",
            width = 392,
            height = 529,
            frame_count = 2,
            repeat_count = 3,
            direction_count = 8,
            animation_speed = 0.4,
            scale = 0.5,
        }
    }
}