---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/9/2023 10:19 PM
---

return {
    folded = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/missile_turret/missile_turret.png",
            width = 496,
            height = 482,
            frame_count = 1,
            direction_count = 16,
            scale = 0.5,
            animation_speed = 0.2,
        },
        shadow = {
            shift = {0.25, 0}
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/missile_turret/missile_turret_teamcolour.png",
            flags = { "mask" },
            width = 496,
            height = 482,
            frame_count = 1,
            direction_count = 16,
            animation_speed = 0.2,
            scale = 0.5,
        }
    },
}