---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/9/2023 10:19 PM
---

return {
    run = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/psi_disruptor/psi_disruptor.png",
            width = 890,
            height = 848,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5
        },
        shadow = {
            shift = {0.25, 0}
        },
        glow = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/psi_disruptor/psi_disruptor_mask.png",
            width = 890,
            height = 848,
            frame_count = 1,
            animation_speed = 0.2,
            direction_count = 1,
            scale = 0.5,
            blend_mode = "additive",
        },
    }
}