---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/9/2023 10:19 PM
---

return {
    run = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/science_facility_physics_lab/science_facility_physics_lab.png",
            width = 812,
            height = 386,
            frame_count = 6,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5
        },
        shadow = {
            shift = {0.25, 0}
        },
        glow = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/science_facility_physics_lab/science_facility_physics_lab_mask.png",
            width = 812,
            height = 386,
            frame_count = 6,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5,
            blend_mode = 'additive',
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/science_facility_physics_lab/science_facility_physics_lab_teamcolour.png",
            flags = { "mask" },
            width = 812,
            height = 386,
            frame_count = 1,
            repeat_count = 6,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5,
        }
    }
}