---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/9/2023 10:19 PM
---

return {
    folding = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/sentry_turret_rockets/sentry_turret_rockets-preparing.png",
            width = 256,
            height = 384,
            frame_count = 10,
            direction_count = 1,
            run_mode = "backward",
            scale = 0.5,
            animation_speed = 0.2,
        },
        shadow = {
            shift = {0.25, 0}
        },
    },
    folded = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/sentry_turret_rockets/sentry_turret_rockets-folded.png",
            width = 256,
            height = 384,
            frame_count = 1,
            direction_count = 1,
            scale = 0.5,
            animation_speed = 0.2,
        },
        shadow = {
            shift = {0.25, 0}
        },
    },
    preparing = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/sentry_turret_rockets/sentry_turret_rockets-preparing.png",
            width = 256,
            height = 384,
            frame_count = 10,
            direction_count = 1,
            scale = 0.5,
            animation_speed = 0.2,
        },
        shadow = {
            shift = {0.25, 0}
        },
    },
    prepared = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/sentry_turret_rockets/sentry_turret_rockets-prepared.png",
            width = 256,
            height = 384,
            frame_count = 1,
            direction_count = 1,
            scale = 0.5,
            animation_speed = 0.2,
        },
        shadow = {
            shift = {0.25, 0}
        },
    },
    attack = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/sentry_turret_rockets/sentry_turret_rockets-attack.png",
            width = 256,
            height = 384,
            frame_count = 1,
            direction_count = 16,
            animation_speed = 0.2,
            scale = 0.5,
        },
        shadow = {
            shift = {0.25, 0}
        },
    }
}