---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 8/9/2023 10:19 PM
---

return {
    run = {
        main = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/starport/starport.png",
            width = 523,
            height = 643,
            frame_count = 12,
            frame_sequence = {1,2,1,2,1,2,3,4,5,2,6,1},
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5
        },
        shadow = {
            shift = {0.25, 0}
        },
        glow = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/starport/starport_mask.png",
            width = 523,
            height = 643,
            frame_count = 12,
            frame_sequence = {1,2,1,2,1,2,3,4,5,2,6,1},
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5,
            blend_mode = "additive",
        },
        team = {
            filename = "__erm_terran_hd_assets__/graphics/entity/buildings/starport/starport_teamcolour.png",
            flags = { "mask" },
            width = 523,
            height = 643,
            frame_count = 1,
            repeat_count = 12,
            direction_count = 1,
            animation_speed = 0.2,
            scale = 0.5,
        }
    }
}